## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np

In [10]:
matrix1 = np.array(([1,2,3],[3,4,5],[5,6,7]))

matrix2 = np.array(([2,2,2],[2,2,2],[2,2,2]))


In [11]:
matrix3 = np.dot(matrix1,matrix2)

matrix3

array([[12, 12, 12],
       [24, 24, 24],
       [36, 36, 36]])

## Write a NumPy program to compute the determinant of a given square array

In [36]:
matrix4 = np.array([[1,2],[5,6]])

matrix4 = matrix4**2

matrix4

array([[ 1,  4],
       [25, 36]], dtype=int32)

In [37]:
matrix4 = np.linalg.det(matrix4) 

matrix4

-63.99999999999998

## Write a NumPy program to compute the cross product of two given vectors

In [26]:
vector1 = [2,3]

vector2 = [4,4]

In [28]:
print (np.cross(vector1,vector2))

-4


## Write a NumPy program to compute the condition number of a given matrix

In [29]:
matrix5 = matrix3

In [30]:
print(np.linalg.cond(matrix5))

1.3831345395498559e+32


## Write a NumPy program to compute the inverse of a given matrix

In [33]:
matrix6 = np.array([[1,2],[2,3]])

In [34]:
print(np.linalg.inv(matrix6))

[[-3.  2.]
 [ 2. -1.]]
